# Generated by Django 5.2.5 on 2025-08-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='coins_logos/')),
                ('foundation_year', models.PositiveIntegerField()),
                ('founder', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('word_count', models.IntegerField()),
                ('char_count', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoinsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('ticker', models.CharField(db_column='Ticker', max_length=10, unique=True)),
                ('interval', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('hihg_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('vwap', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('trade_count', models.IntegerField(blank=True, null=True)),
                ('coin', models.ForeignKey(blank=True, db_column='ticker', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='coin_app.coininfo', to_field='ticker')),
            ],
            options={
                'ordering': ['Name'],
                'permissions': [('can_addministrate_lib', 'User can administrate coin DB'), ('can_correct_info', 'User can correct some price')],
                'indexes': [models.Index(fields=['ticker', 'interval', 'timestamp'], name='coin_app_co_Ticker_940397_idx')],
                'unique_together': {('ticker', 'interval', 'timestamp')},
            },
        ),
    ]
