# Generated by Django 5.2.5 on 2025-08-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
