# Generated by Django 5.2.5 on 2025-08-20 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 14, 22, 36, 871282, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
