# Generated by Django 5.2.5 on 2025-08-20 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_adminuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
