# Generated by Django 5.2.5 on 2025-08-21 14:38
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

content_type_global, created = ContentType.objects.get_or_create(app_label = 'users_app', model = 'global')

def add_permissions(apps, schema_editor):
    

    Permission.objects.create(
        codename = 'can_manage_users',
        name = 'Can manage users',
        content_type = content_type_global
    )

    Permission.objects.create(
        codename = 'can_add_permission_users',
        name = 'Can add permissions for users',
        content_type = content_type_global
    )

    Permission.objects.create(
        codename = 'can_access_users_list',
        name = 'Can access',
        content_type = content_type_global
    )

def rollback_permissions(apps, schema_editor):
    Permission.objects.filter( 
        content_type = content_type_global,
        codename__in =['can_manage_users','can_add_permission_users','can_access_users_list']
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_adminuser_date_joined'),
    ]

    operations = [
        migrations.RunPython(
            code = add_permissions,
            reverse_code=rollback_permissions
        ),
    ]
